"project_id": "515826"
"base_path": "."
"base_url": "https://api.crowdin.com"
"commit_message": "🌐 Updated %language%"
"append_commit_message": false
"pull_request_labels": ["translation"]

"preserve_hierarchy": true

files: [
 {
  "source": "/i18n/*/en.yml",
  "translation": "/%original_path%/%two_letters_code%.yml",
  "skip_untranslated_strings": true,
  "export_only_approved": true
 }
]