project_id: CROWDIN_PERSONAL_TOKEN
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"
commit_message: "🌐 Updated %language%"
append_commit_message: false

preserve_hierarchy: true

files: [
 {
  source: "/i18n/*/en.yml",
  translation: "/%original_path%/%two_letters_code%.yml",
  skip_untranslated_strings: true,
  export_only_approved: true,
  escape_quotes: 1,
  escape_special_characters: 1
 }
]