project_id: '515826'
base_path: .
base_url: 'https://api.crowdin.com'
commit_message: "fix(i18n): updated %language%"
append_commit_message: 
preserve_hierarchy: 1
files:
  - source: /i18n/*/en.yml
    translation: /%original_path%/%two_letters_code%.yml
    escape_quotes: 1
    escape_special_characters: 1
