[tool.commitizen]
name = "cz_conventional_commits"
version = "1.11.0"
tag_format = "$version"
changelog_start_rev = "aa6eaaee2467fe8f2e26151fc930ec49cdea027b"
update_changelog_on_bump = true

[tool.ruff]
fix = true
ignore = ["E999", "E501", "E722"]
exclude = [
    ".git",
    ".ruff_cache",
    "__pypackages__",
]
