questions = [
    "If you could have dinner with any historical figure, who would it be and why?",
    "If you could only eat one type of cuisine for the rest of your life, what would it be?",
    "If you could only listen to one genre of music for the rest of your life, what would it be?",
    "If you could only play one sport for the rest of your life, what would it be?",
    "If you could only play one video game for the rest of your life, what would it be?",
    "If you could only read one book for the rest of your life, what would it be?",
    "If you could only use one mode of transportation for the rest of your life, what would it be?",
    "If you could only use one online shopping site for the rest of your life, which one would it be?",
    "If you could only use one payment app for the rest of your life, which one would it be?",
    "If you could only use one phone app for the rest of your life, which one would it be?",
    "If you could only use one productivity app for the rest of your life, which one would it be",
    "If you could only use one search engine for the rest of your life, which one would it be?",
    "If you could only use one social media platform for the rest of your life, which one would it be?",
    "If you could only use one streaming service for the rest of your life, which one would it be?",
    "If you could only visit one country for the rest of your life, where would it be?",
    "If you could only watch one movie for the rest of your life, what would it be?",
    "If you could only watch one TV show for the rest of your life, what would it be?",
    "If you could only wear one type of clothing for the rest of your life, what would it be?",
    "If you could switch lives with any celebrity, who would it be and why?",
    "What is the best compliment you've ever received?",
    "What is the craziest dream you've ever had?",
    "What is the most adventurous mode of transportation you've ever used?",
    "What is the most adventurous thing you've ever eaten?",
    "What is the most memorable book you've ever read?",
    "What is the most memorable gift you've ever received?",
    "What is the most memorable trip you've ever taken?",
    "What is the most memorable TV show you've ever watched?",
    "What is the most memorable video game you've ever played?",
    "What is the most spontaneous thing you've ever done?",
    "Would you rather be able to breathe underwater or fly?",
    "Would you rather be able to communicate with animals or speak any language fluently?",
    "Would you rather be able to control fire or control water?",
    "Would you rather be able to control the weather or control time?",
    "Would you rather be able to fly or be invisible?",
    "Would you rather be able to read minds or control them?",
    "Would you rather be able to shapeshift into any animal or have the ability to communicate with ghosts?",
    "Would you rather be able to shapeshift into any animal or have the ability to teleport?",
    "Would you rather be able to teleport or turn invisible at will?",
    "Would you rather be able to turn invisible at will or have super speed?",
    "Would you rather be able to turn invisible or teleport?",
    "Would you rather have super hearing or super sight?",
    "Would you rather have super strength or super speed?",
    "Would you rather have super strength or the ability to fly?",
    "Would you rather have the ability to breathe underwater or fly?",
    "Would you rather have the ability to communicate with animals or the ability to speak any language fluently?",
    "Would you rather have the ability to communicate with plants or the ability to communicate with ghosts?",
    "Would you rather have the ability to fly or the ability to breathe underwater?",
    "Would you rather have the ability to read minds or control them?",
    "Would you rather have the power of super strength or the power of invincibility?",
    "Would you rather have the power of telekinesis or the ability to breathe underwater?",
    "Would you rather have the power of telekinesis or the power of pyrokinesis?",
    "What is your favorite kind of fruit?",
    "Do you have a favorite stuffed animal?",
    "Do you have a favorite story or movie?",
    "What is your favorite thing to do inside?",
    "Do you have a favorite game to play at home?",
    "Do you have a favorite picture or drawing that you've made?",
    "What is your favorite kind of music?",
    "Do you have a favorite restaurant or place to eat?",
    "What is your favorite thing to do at the beach or pool?",
    "Do you have a favorite season of the year?",
    "What is your favorite kind of weather?",
    "Do you have a favorite kind of sports or physical activity?",
    "What is your favorite thing to do on a special occasion, like a birthday or holiday?",
    "Do you have a favorite kind of food for breakfast, lunch, or dinner?",
    "Do you have a favorite activity or hobby that you like to do with your family?",
    "What is your favorite kind of vacation or trip to go on?",
    "Do you have a favorite place to go to in your town or city?",
    "What is your favorite thing to do on a rainy day?",
    "Do you have a favorite kind of snack?",
    "Have you ever actually kept a New Year's resolution?",
    "Where's the most uncomfortable place you've ever slept?",
    "Where do you waste the most time online?",
    "What's the most useless piece of knowledge you know?",
    "Have you traveled anywhere recently, or do you have any trips planned?",
    "What's something interesting about you that most people don't know?",
    "What's your favorite thing about where you grew up?",
    "If you could be any character from a book or movie, who would you be and why?",
    "If you could have any job in the world, what would it be?",
    "If you could have any job in the world, what would it be and why?",
    "If you could travel to any planet, which one would you choose and why?",
    "If you could live in any era, which one would you choose and why?",
    "If you could meet any fictional character, who would it be and why?",
    "If you could live in any house or apartment from a movie or TV show, which one would you choose and why?",
    "If you could learn any instrument in the world, which one would you choose and why?",
    "If you could be any character from a book, who would you be and why?",
    "If you could have any pet, real or fictional, which one would you choose and why?",
    "If you could go back in time and change one event, what would it be and why?",
    "If you could go forward in time and see one event, what would it be and why?",
    "If you could invent a new holiday, what would it be and how would you celebrate it?",
    "If you could rename yourself, what name would you choose and why?",
    "If you could switch lives with one person for a day, who would you choose and why?",
    "If you could switch places with any animal, which one would you choose and why?",
    "If you could be any age for the rest of your life, what age would you choose and why?",
    "If you could only eat one type of fruit for the rest of your life, what would it be and why?",
    "If you could only use one type of transportation for the rest of your life, what would it be and why?",
    "If you could only watch one type of TV show for the rest of your life, what genre would it be and why?",
    "If you could only play one type of video game for the rest of your life, what genre would it be and why?",
    "If you could only listen to one type of music for the rest of your life, what genre would it be and why?",
    "What's your favorite thing about your job or school?",
    "What's the best gift you've ever received?",
    "What's the best concert you've ever been to?",
    "Do you have any phobias or irrational fears?",
    "What is your favorite thing about yourself and why?",
    "What is your favorite thing about your family and why?",
    "If you could have any animal as a pet, which one would you choose and why?",
    "If you could only eat one type of food for the rest of your life, what would it be and why?",
    "What is your favorite memory from childhood and why?",
    "If you could learn any new skill, what would it be and why?",
    "If you could be any age for the rest of your life, what age would you choose and why?",
    "If you could travel back in time and visit any era, which one would you choose and why?",
    "What is your favorite thing about your job or school and why?",
    "What is your favorite thing about your friends and why?",
    "If you could be any character from a book or movie, who would you be and why?",
    "What do you prefer? Apple or Android?",
    "What do you prefer? PC or Console?",
    "What do you prefer? AAA or Indie Games?",
]
