name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run linter
        run: |
          python -m pip install black
          black . 
      #- name: Check Diff
      #  id: check_diff
      #  run: |
      #    git diff . || echo "::set-output name=diff::true"
      - name: Commit and Push
        #if: steps.check_diff.outputs.diff == 'true'
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "🚨 Linting"
          git push
